'use client';
import {useEffect,useState} from 'react';
import {ShieldCheck,Mail,Terminal,Code2,ArrowUpRight,ArrowRight,Check,Clock3,Flame,Zap,RotateCcw,BookOpen,CheckCircle2,AlertCircle,LoaderCircle} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Progress} from '@/components/ui/progress';
import type {PublicChallenge} from '@/lib/challenges';
type Result={id:string;answer:number;score:number;correctIndex:number;explanation:string;takeaway:string};
type Stats={total:number;completed:number;streak:number};
type Daily={day:string;source:string;signedIn:boolean;challenges:PublicChallenge[];results:Result[];stats:Stats};
const kinds={phishing:{label:'Phishing detection',short:'Phishing',icon:Mail,file:'inbox / suspicious-message.eml',time:'3 min'},logs:{label:'Log analysis',short:'Logs',icon:Terminal,file:'evidence / authentication.log',time:'4 min'},code:{label:'Secure code review',short:'Code review',icon:Code2,file:'review / products.js',time:'3 min'}};
export default function CyberDaily(){
 const [daily,setDaily]=useState<Daily|null>(null),[active,setActive]=useState('phishing'),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[remaining,setRemaining]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/daily',{cache:'no-store'});const d=await r.json() as Daily & {error?:string};if(!r.ok)throw new Error(d.error);setDaily(d);}catch(e){setError(e instanceof Error?e.message:'Unable to load challenges.');}finally{setLoading(false);}}
 useEffect(()=>{void load();const tick=()=>{const n=new Date();const ms=Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),n.getUTCDate()+1)-n.getTime();setRemaining(`${Math.floor(ms/3600000).toString().padStart(2,'0')}:${Math.floor(ms/60000%60).toString().padStart(2,'0')}:${Math.floor(ms/1000%60).toString().padStart(2,'0')}`);};tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!daily)return;const timer=setInterval(()=>{if(new Date().toISOString().slice(0,10)!==daily.day){setAnswer('');void load();}},30000);return()=>clearInterval(timer);},[daily?.day]);
 const challenge=daily?.challenges.find(c=>c.id===active),result=daily?.results.find(r=>r.id===active),done=daily?.results.length||0;
 async function submit(){if(!daily||!challenge||answer==='')return;setBusy(true);setError('');try{const r=await fetch('/api/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({day:daily.day,id:challenge.id,answer:Number(answer)})});const d=await r.json() as {result:Result;stats:Stats;error?:string};if(!r.ok)throw new Error(d.error);setDaily(prev=>prev?{...prev,results:[...prev.results.filter(x=>x.id!==d.result.id),d.result],stats:d.stats}:prev);}catch(e){setError(e instanceof Error?e.message:'Unable to save your answer.');}finally{setBusy(false);}}
 function change(value:string){setActive(value);setAnswer('');setError('');}
 return <div className="site-shell">
  <header className="site-header"><a className="brand" href="/" aria-label="CyberDaily home"><span className="brand-mark"><ShieldCheck size={24}/></span>Cyber<span>Daily</span><span className="beta">BETA</span></a><div className="header-right"><span className="desktop-only">A little practice. A sharper instinct.</span><span className="profile"><ShieldCheck size={16}/> {daily?.signedIn?'Your training space':'Daily practice'}</span></div></header>
  <main className="main-wrap"><div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/> DAILY SECURITY PRACTICE</div><h1>Stay sharp. <span>Every day.</span></h1><p>Three small challenges. Real-world security instincts.</p></div><div className="reset"><span><Clock3 size={15}/> NEXT CHALLENGES</span><strong>{remaining||'--:--:--'}</strong><small>Resets at 00:00 UTC</small></div></div>
   <div className="workspace-grid"><section className="daily-workspace" aria-label="Daily challenges">
    <div className="daily-bar"><div><span className="eyebrow">TODAY’S MISSION</span><h2>{daily?new Date(daily.day+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}):'Your daily challenge set'}</h2></div><span className="pill"><Clock3 size={14}/> 10 minutes</span></div>
    {loading?<div className="load-state" role="status"><LoaderCircle className="spin" size={26}/><h3>Preparing your mission</h3><p>Loading today’s challenges and your saved progress.</p></div>:!daily?<div className="load-state"><AlertCircle/><h3>We couldn’t load your mission</h3><p role="alert">{error}</p><button className="secondary-button" onClick={load}><RotateCcw size={16}/> Try again</button></div>:<>
     <Tabs value={active} onValueChange={change}><TabsList className="challenge-tabs" aria-label="Challenge type">{(['phishing','logs','code'] as const).map((id,i)=>{const Icon=kinds[id].icon;const complete=daily.results.some(r=>r.id===id);return <TabsTrigger key={id} value={id} className="challenge-tab"><span className="tab-number">{complete?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><Icon size={17}/><span>{kinds[id].short}</span></TabsTrigger>;})}</TabsList>
     {daily.challenges.map(c=><TabsContent value={c.id} key={c.id} className="challenge-body"><div className="challenge-meta"><span className="category">{kinds[c.id].label}</span><span className="difficulty">{c.difficulty}</span><span>{kinds[c.id].time}</span><span className="points"><Zap size={14}/>100 XP</span></div><h2 className="challenge-title">{c.title}</h2><p className="briefing">{c.briefing}</p><div className={'evidence '+(c.id==='phishing'?'email-evidence':'')}><div className="evidence-header">{(()=>{const Icon=kinds[c.id].icon;return <Icon size={16}/>;})()}<span>{kinds[c.id].file}</span><span className="read-only">READ ONLY</span></div><pre>{c.evidence}</pre></div>
      <div className="answer-section"><div className="eyebrow">YOUR CALL</div><h3 id={`question-${c.id}`}>{c.question}</h3><RadioGroup aria-labelledby={`question-${c.id}`} value={result?String(result.answer):answer} onValueChange={setAnswer} disabled={Boolean(result)||busy} className="answer-options">{c.options.map((o,i)=><label key={i} className={'answer-option '+((result?result.answer===i:answer===String(i))?'selected ':'')+(result&&result.correctIndex===i?'correct ':'')+(result&&result.answer===i&&result.score===0?'incorrect':'')} htmlFor={`${c.id}-${i}`}><RadioGroupItem value={String(i)} id={`${c.id}-${i}`}/><span className="option-letter">{String.fromCharCode(65+i)}</span><span>{o}</span>{result&&result.correctIndex===i&&<CheckCircle2 size={18}/>}</label>)}</RadioGroup></div>
      {error&&<p className="error" role="alert">{error}</p>}
      {result?<div className={'result-panel '+(result.score?'success':'learn')} role="status"><div className="result-title">{result.score?<CheckCircle2/>:<BookOpen/>}<h3>{result.score?'Good catch. +100 XP':'A useful lesson for next time.'}</h3></div><p>{result.explanation}</p><div className="takeaway"><strong>TAKE IT WITH YOU</strong><p>{result.takeaway}</p></div>{done<3&&<button className="primary-button" onClick={()=>change(daily.challenges.find(x=>!daily.results.some(r=>r.id===x.id))!.id)}>Next challenge <ArrowRight size={17}/></button>}</div>:<div className="submit-row"><span>One answer. Make it count.</span>{daily.signedIn?<button className="primary-button" disabled={answer===''||busy} onClick={submit}>{busy?'Saving…':'Lock in answer'}{busy?<LoaderCircle className="spin" size={17}/>:<ArrowRight size={17}/>}</button>:<a className="primary-button" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in to answer <ArrowUpRight size={17}/></a>}</div>}
     </TabsContent>)}
     </Tabs><div className="source-note">{daily.source==='prepared'?'Daily challenge set • prepared in advance • fictional training scenarios':'Starter practice set • today’s prepared challenges are not available yet.'}</div></>}
   </section>
   <aside className="right-rail"><section className="progress-card"><div className="rail-title"><span className="eyebrow">YOUR DAILY PROGRESS</span><ShieldCheck size={19}/></div><div className="progress-total"><strong>{done}<span>/ 3</span></strong><span>challenges<br/>completed</span></div><Progress value={done/3*100} className="daily-progress"/><div className="mission-list">{(['phishing','logs','code'] as const).map(id=>{const Icon=kinds[id].icon;const complete=daily?.results.some(r=>r.id===id);return <button key={id} onClick={()=>change(id)} className={active===id?'current':''}><Icon size={17}/><span>{kinds[id].label}</span>{complete?<CheckCircle2 size={17} className="lime"/>:<span className="empty-circle"/>}</button>;})}</div><div className="daily-score"><span>Today’s XP</span><strong>{daily?.results.reduce((sum,r)=>sum+r.score,0)||0}<span> / 300</span></strong></div>{done===3&&<div className="complete-note"><CheckCircle2 size={20}/><div><strong>Mission complete.</strong><p>Come back tomorrow for another round.</p></div></div>}</section>
    <section className="stats-card"><div><Flame className="orange" size={22}/><strong>{daily?.stats.streak||0}<span>day streak</span></strong></div><div><Zap className="lime" size={22}/><strong>{daily?.stats.total||0}<span>total XP</span></strong></div></section>
    <section className="field-note"><div className="eyebrow"><BookOpen size={16}/> FIELD NOTES</div><h3>Build the habit.<br/>Trust the evidence.</h3><p>Read closely, make a call, then learn the reasoning behind it.</p><div className="note-rule"/><p className="small-note">Earn 100 XP for each correct answer. Complete all three to build your streak—even when you get one wrong.</p></section>
    <p className="rail-footnote"><ShieldCheck size={15}/> A safe place to make mistakes.<br/>All scenarios are fictional.</p>
   </aside></div>
  </main><footer><span>CyberDaily <span className="footer-slash">/</span> Make security second nature.</span><span>One day. Three challenges. Better instincts.</span></footer>
 </div>;
}


