import { z } from 'zod';
export const challengeSchema = z.object({
 id:z.enum(['phishing','logs','code']), title:z.string().min(5).max(90), difficulty:z.enum(['Beginner','Intermediate']),
 briefing:z.string().min(20).max(800), evidence:z.string().min(20).max(4000), question:z.string().min(10).max(300),
 options:z.array(z.string().min(2).max(350)).length(4), correctIndex:z.number().int().min(0).max(3),
 explanation:z.string().min(30).max(1600), takeaway:z.string().min(15).max(500),
});
export const packSchema=z.object({challenges:z.array(challengeSchema).length(3)}).refine(p=>new Set(p.challenges.map(c=>c.id)).size===3,'One of each type required');
export type Challenge=z.infer<typeof challengeSchema>;
export type PublicChallenge=Omit<Challenge,'correctIndex'|'explanation'|'takeaway'>;
export function publicChallenge(c:Challenge):PublicChallenge {const {correctIndex,explanation,takeaway,...safe}=c;return safe;}
export function utcDay(date=new Date()){return date.toISOString().slice(0,10);}
export function previousDay(day:string){return utcDay(new Date(Date.parse(day+'T00:00:00Z')-86400000));}
export const starterPack:Challenge[]=[
 {id:'phishing',title:'The invoice that couldn’t wait',difficulty:'Beginner',briefing:'You work at Northstar Studio. An email claiming to be from your finance team has landed in your inbox. Decide how to handle it.',evidence:'From: Finance Team <accounts@northstar-billing.example>\nTo: you@northstar.example\nSubject: ACTION REQUIRED: Overdue invoice #1048\n\nHi,\nOur bank details have changed. Please settle the attached invoice today to avoid service suspension.\n\nConfirm your work password at:\nhttps://northstar-verify.example/invoice\n\nPlease don’t call — the finance team is in meetings.\nThanks, Finance',question:'What is the safest next step?',options:['Open the link and sign in to check the invoice','Reply to the email asking for the new bank details','Report the message and verify through a known finance contact','Pay now and verify the invoice later'],correctIndex:2,explanation:'The sender uses a different domain from northstar.example, asks for a password, creates urgency and discourages independent verification. Report it and contact finance using a number or channel you already trust. A reply would return to the suspicious sender.',takeaway:'Verify urgent payment or credential requests through a separate, trusted channel.'},
 {id:'logs',title:'One login too many',difficulty:'Intermediate',briefing:'You are reviewing authentication alerts for a small business. All timestamps are UTC. Identify the sequence that warrants an immediate investigation.',evidence:'09:41:02  192.0.2.18     user=alex  LOGIN_SUCCESS  mfa=pass\n09:42:11  203.0.113.44   user=admin LOGIN_FAILED   reason=password\n09:42:12  203.0.113.44   user=admin LOGIN_FAILED   reason=password\n09:42:13  203.0.113.44   user=admin LOGIN_FAILED   reason=password\n09:42:14  203.0.113.44   user=admin LOGIN_SUCCESS  mfa=disabled\n09:42:20  203.0.113.44   user=admin EXPORT_USERS   rows=2481\n09:44:10  192.0.2.19     user=sam   LOGIN_SUCCESS  mfa=pass',question:'Which observation is the strongest signal of a possible compromise?',options:['Alex and Sam signed in from different addresses','Repeated admin failures followed by success and a large export','The log entries use UTC timestamps','Two users passed their MFA checks'],correctIndex:1,explanation:'The same source rapidly tries the admin account, succeeds without MFA and immediately exports user records. That sequence suggests a possible account takeover and data access. Preserve evidence, validate whether the activity was authorised and contain the account if appropriate. Logs alone do not establish every fact.',takeaway:'Correlate failed logins, successful access and subsequent actions instead of treating each event in isolation.'},
 {id:'code',title:'A query with a hidden risk',difficulty:'Beginner',briefing:'A teammate asks you to review a product lookup endpoint before release. The query parameter comes directly from the visitor.',evidence:'// Product lookup — simplified JavaScript\napp.get("/products", async (req, res) => {\n  const name = req.query.name;\n  const sql = "SELECT * FROM products WHERE name = \'"\n    + name + "\'";\n  const rows = await db.query(sql);\n  res.json(rows);\n});',question:'Which change best addresses the vulnerability?',options:['Remove spaces from the visitor’s input','Hide the database error message','Encode the input as Base64 before adding it to the query','Use a parameterised query and bind the input as a value'],correctIndex:3,explanation:'Concatenating untrusted input into SQL lets that input change the query’s structure. A parameterised query keeps SQL syntax separate from bound data. Removing spaces, encoding the input or hiding errors does not provide this separation.',takeaway:'Treat user input as data. Use your database library’s parameter binding rather than building SQL strings.'},
];
